// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VienHoa_Infrastructure.DataEx;

#nullable disable

namespace VienHoa_Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230819170919_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VienHoa_Core.Entity.ChatThai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("LoaiChatThaiId")
                        .HasColumnType("int");

                    b.Property<string>("TenChatThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoaiChatThaiId");

                    b.ToTable("chatThais");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.DoanhNghiep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiLienHe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCongTy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("doanhNghieps");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.DonViDoTheoNam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TenDonVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("donViDoTheoNams");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.DuAn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DoanhNghiepId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDuAn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoanhNghiepId");

                    b.ToTable("duAns");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.GayNongLenToanCau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("GiaTri")
                        .HasColumnType("float");

                    b.Property<int>("KhiPhatThaiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhiPhatThaiId");

                    b.ToTable("gayNongLenToanCaus");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.HeSoPhatThaiDien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("GiaTri")
                        .HasColumnType("float");

                    b.Property<int>("KhiPhatThaiId")
                        .HasColumnType("int");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhiPhatThaiId");

                    b.ToTable("heSoPhatThaiDiens");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.HeSoPhatThaiTuNguyenLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DonViTinhId")
                        .HasColumnType("int");

                    b.Property<double>("GiaTri")
                        .HasColumnType("float");

                    b.Property<int>("KhiPhatThaiId")
                        .HasColumnType("int");

                    b.Property<int>("NguyenLieuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhiPhatThaiId");

                    b.HasIndex("NguyenLieuId");

                    b.ToTable("heSoPhatThaiTuNguyenLieus");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.HeSoPhatThaiTuNhienLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DonViTinhId")
                        .HasColumnType("int");

                    b.Property<double>("GiaTri")
                        .HasColumnType("float");

                    b.Property<int>("KhiPhatThaiId")
                        .HasColumnType("int");

                    b.Property<int>("NhienLieuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhiPhatThaiId");

                    b.HasIndex("NhienLieuId");

                    b.ToTable("heSoPhatThaiTuNhienLieus");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.KhiPhatThai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TenKhi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("khiPhatThais");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.LCA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("KyHieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLCA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LCAs");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.LoaiChatThai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TenLoaiChatThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("loaiChatThais");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.LoaiLoNung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TenLoaiLo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("loaiLoNungs");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.LoaiNguyenLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("loaiNguyenLieus");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.LoaiNhaMay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("loaiNhaMays");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.LoaiNhienLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("loaiNhienLieus");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.LoNungTrongNhaMay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("LoaiLoNungId")
                        .HasColumnType("int");

                    b.Property<int>("NhaMayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoaiLoNungId");

                    b.HasIndex("NhaMayId");

                    b.ToTable("loNungTrongNhaMays");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.NguyenLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DonViDoTheoNamId")
                        .HasColumnType("int");

                    b.Property<int>("LoaiNguyenLieuId")
                        .HasColumnType("int");

                    b.Property<string>("TenHienThiTieuThu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguyenLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DonViDoTheoNamId");

                    b.HasIndex("LoaiNguyenLieuId");

                    b.ToTable("nguyenLieus");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.NguyenLieuNam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("SanXuatNamId")
                        .HasColumnType("int");

                    b.Property<double>("SoLuong")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SanXuatNamId");

                    b.ToTable("nguyenLieuNams");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.NguyenLieuSanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DonViId")
                        .HasColumnType("int");

                    b.Property<int>("NguyenLieuId")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<double>("SoLuong")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("NguyenLieuId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("nguyenLieuSanPhams");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.NhaMay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CongSuatThietKeId")
                        .HasColumnType("int");

                    b.Property<int>("DoanhNghiepId")
                        .HasColumnType("int");

                    b.Property<int>("LoaiLoNungId")
                        .HasColumnType("int");

                    b.Property<int>("LoaiNhaMayId")
                        .HasColumnType("int");

                    b.Property<string>("TenNhaMay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TiLeCoPhan")
                        .HasColumnType("float");

                    b.Property<string>("ViTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoanhNghiepId");

                    b.HasIndex("LoaiLoNungId");

                    b.HasIndex("LoaiNhaMayId");

                    b.ToTable("nhaMays");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.NhienLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DonViDoTheoNamId")
                        .HasColumnType("int");

                    b.Property<int>("LoaiNhienLieuId")
                        .HasColumnType("int");

                    b.Property<double>("NhietTriRieng")
                        .HasColumnType("float");

                    b.Property<string>("TenHienThiTieuThu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhienLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DonViDoTheoNamId");

                    b.HasIndex("LoaiNhienLieuId");

                    b.ToTable("nhienLieus");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.NhienLieuSanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DonViId")
                        .HasColumnType("int");

                    b.Property<int>("NhienLieuId")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<double>("SoLuong")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("NhienLieuId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("nhienLieuSanPhams");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.RanhGioiLCA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("LCAId")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LCAId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("ranhGioiLCAs");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CongNghe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CongSuatThietKe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DuAnId")
                        .HasColumnType("int");

                    b.Property<string>("KyHieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiLoNungId")
                        .HasColumnType("int");

                    b.Property<string>("MaCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NhaMayId")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DuAnId");

                    b.HasIndex("LoaiLoNungId");

                    b.HasIndex("NhaMayId");

                    b.ToTable("sanPhams");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.SanXuatNam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("DBKK_SanXuatDienNang")
                        .HasColumnType("float");

                    b.Property<double>("DBKK_TieuThuDienNang")
                        .HasColumnType("float");

                    b.Property<double>("DBKK_TieuThuNguyenLieu")
                        .HasColumnType("float");

                    b.Property<double>("DBKK_TieuThuNhienLieu")
                        .HasColumnType("float");

                    b.Property<int>("NamSanXuat")
                        .HasColumnType("int");

                    b.Property<int>("NhaMayId")
                        .HasColumnType("int");

                    b.Property<double>("SLSP_LuongBanRa")
                        .HasColumnType("float");

                    b.Property<double>("SLSP_LuongLuuKho")
                        .HasColumnType("float");

                    b.Property<double>("SLSP_LuongMuaVao")
                        .HasColumnType("float");

                    b.Property<double>("SLSP_SanLuongSanPham")
                        .HasColumnType("float");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<double>("TTDN_TongLuongDien")
                        .HasColumnType("float");

                    b.Property<double>("TTDN_TongLuongSH")
                        .HasColumnType("float");

                    b.Property<double>("TTDN_TongLuongSX")
                        .HasColumnType("float");

                    b.Property<double>("TTDN_TongLuongTuSX")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("NhaMayId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("sanXuatNams");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.ThaiDauRa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ChatThaiId")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<double>("SoLuong")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ChatThaiId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("thaiDauRas");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.TieuThuNhienLieuLoNam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("NamSanXuat")
                        .HasColumnType("int");

                    b.Property<int>("NhaMayId")
                        .HasColumnType("int");

                    b.Property<double>("SoLuong")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("NhaMayId");

                    b.ToTable("tieuThuNhienLieuLoNams");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.ChatThai", b =>
                {
                    b.HasOne("VienHoa_Core.Entity.LoaiChatThai", "LoaiChatThai")
                        .WithMany("ChatThais")
                        .HasForeignKey("LoaiChatThaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiChatThai");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.DuAn", b =>
                {
                    b.HasOne("VienHoa_Core.Entity.DoanhNghiep", "DoanhNghiep")
                        .WithMany("DuAns")
                        .HasForeignKey("DoanhNghiepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoanhNghiep");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.GayNongLenToanCau", b =>
                {
                    b.HasOne("VienHoa_Core.Entity.KhiPhatThai", "KhiPhatThai")
                        .WithMany("GayNongLenToanCaus")
                        .HasForeignKey("KhiPhatThaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhiPhatThai");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.HeSoPhatThaiDien", b =>
                {
                    b.HasOne("VienHoa_Core.Entity.KhiPhatThai", "KhiPhatThai")
                        .WithMany("HeSoPhatThaiDiens")
                        .HasForeignKey("KhiPhatThaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhiPhatThai");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.HeSoPhatThaiTuNguyenLieu", b =>
                {
                    b.HasOne("VienHoa_Core.Entity.KhiPhatThai", "KhiPhatThai")
                        .WithMany("HeSoPhatThaiTuNguyenLieus")
                        .HasForeignKey("KhiPhatThaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VienHoa_Core.Entity.NguyenLieu", "NguyenLieu")
                        .WithMany("HeSoPhatThaiTuNguyenLieus")
                        .HasForeignKey("NguyenLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhiPhatThai");

                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.HeSoPhatThaiTuNhienLieu", b =>
                {
                    b.HasOne("VienHoa_Core.Entity.KhiPhatThai", "KhiPhatThai")
                        .WithMany("HeSoPhatThaiTuNhienLieus")
                        .HasForeignKey("KhiPhatThaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VienHoa_Core.Entity.NhienLieu", "NhienLieu")
                        .WithMany("HeSoPhatThaiTuNhienLieus")
                        .HasForeignKey("NhienLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhiPhatThai");

                    b.Navigation("NhienLieu");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.LoNungTrongNhaMay", b =>
                {
                    b.HasOne("VienHoa_Core.Entity.LoaiLoNung", "LoaiLoNung")
                        .WithMany("LoNungTrongNhaMays")
                        .HasForeignKey("LoaiLoNungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VienHoa_Core.Entity.NhaMay", "NhaMay")
                        .WithMany("LoNungTrongNhaMays")
                        .HasForeignKey("NhaMayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoaiLoNung");

                    b.Navigation("NhaMay");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.NguyenLieu", b =>
                {
                    b.HasOne("VienHoa_Core.Entity.DonViDoTheoNam", "DonViDoTheoNam")
                        .WithMany()
                        .HasForeignKey("DonViDoTheoNamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VienHoa_Core.Entity.LoaiNguyenLieu", "LoaiNguyenLieu")
                        .WithMany("NguyenLieus")
                        .HasForeignKey("LoaiNguyenLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonViDoTheoNam");

                    b.Navigation("LoaiNguyenLieu");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.NguyenLieuNam", b =>
                {
                    b.HasOne("VienHoa_Core.Entity.SanXuatNam", "SanXuatNam")
                        .WithMany("NguyenLieuNams")
                        .HasForeignKey("SanXuatNamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanXuatNam");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.NguyenLieuSanPham", b =>
                {
                    b.HasOne("VienHoa_Core.Entity.NguyenLieu", "NguyenLieu")
                        .WithMany("NguyenLieuSanPhams")
                        .HasForeignKey("NguyenLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VienHoa_Core.Entity.SanPham", "SanPham")
                        .WithMany("NguyenLieuSanPhams")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguyenLieu");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.NhaMay", b =>
                {
                    b.HasOne("VienHoa_Core.Entity.DoanhNghiep", "DoanhNghiep")
                        .WithMany("NhaMays")
                        .HasForeignKey("DoanhNghiepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VienHoa_Core.Entity.LoaiLoNung", "LoaiLoNung")
                        .WithMany("NhaMays")
                        .HasForeignKey("LoaiLoNungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VienHoa_Core.Entity.LoaiNhaMay", "LoaiNhaMay")
                        .WithMany("NhaMays")
                        .HasForeignKey("LoaiNhaMayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoanhNghiep");

                    b.Navigation("LoaiLoNung");

                    b.Navigation("LoaiNhaMay");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.NhienLieu", b =>
                {
                    b.HasOne("VienHoa_Core.Entity.DonViDoTheoNam", "DonViDoTheoNam")
                        .WithMany()
                        .HasForeignKey("DonViDoTheoNamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VienHoa_Core.Entity.LoaiNhienLieu", "LoaiNhienLieu")
                        .WithMany("NhienLieus")
                        .HasForeignKey("LoaiNhienLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonViDoTheoNam");

                    b.Navigation("LoaiNhienLieu");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.NhienLieuSanPham", b =>
                {
                    b.HasOne("VienHoa_Core.Entity.NhienLieu", "NhienLieu")
                        .WithMany("NhienLieuSanPhams")
                        .HasForeignKey("NhienLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VienHoa_Core.Entity.SanPham", "SanPham")
                        .WithMany("NhienLieuSanPhams")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhienLieu");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.RanhGioiLCA", b =>
                {
                    b.HasOne("VienHoa_Core.Entity.LCA", "LCA")
                        .WithMany("RanhGioiLCAs")
                        .HasForeignKey("LCAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VienHoa_Core.Entity.SanPham", "SanPham")
                        .WithMany("RanhGioiLCAs")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LCA");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.SanPham", b =>
                {
                    b.HasOne("VienHoa_Core.Entity.DuAn", "DuAn")
                        .WithMany()
                        .HasForeignKey("DuAnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VienHoa_Core.Entity.LoaiLoNung", "LoaiLoNung")
                        .WithMany()
                        .HasForeignKey("LoaiLoNungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VienHoa_Core.Entity.NhaMay", "NhaMay")
                        .WithMany("SanPhams")
                        .HasForeignKey("NhaMayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DuAn");

                    b.Navigation("LoaiLoNung");

                    b.Navigation("NhaMay");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.SanXuatNam", b =>
                {
                    b.HasOne("VienHoa_Core.Entity.NhaMay", "NhaMay")
                        .WithMany()
                        .HasForeignKey("NhaMayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VienHoa_Core.Entity.SanPham", "SanPham")
                        .WithMany("SanXuatNams")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhaMay");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.ThaiDauRa", b =>
                {
                    b.HasOne("VienHoa_Core.Entity.ChatThai", "ChatThai")
                        .WithMany("ThaiDauRas")
                        .HasForeignKey("ChatThaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VienHoa_Core.Entity.SanPham", "SanPham")
                        .WithMany("ThaiDauRas")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatThai");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.TieuThuNhienLieuLoNam", b =>
                {
                    b.HasOne("VienHoa_Core.Entity.NhaMay", "NhaMay")
                        .WithMany("TieuThuNhienLieuLoNams")
                        .HasForeignKey("NhaMayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaMay");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.ChatThai", b =>
                {
                    b.Navigation("ThaiDauRas");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.DoanhNghiep", b =>
                {
                    b.Navigation("DuAns");

                    b.Navigation("NhaMays");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.KhiPhatThai", b =>
                {
                    b.Navigation("GayNongLenToanCaus");

                    b.Navigation("HeSoPhatThaiDiens");

                    b.Navigation("HeSoPhatThaiTuNguyenLieus");

                    b.Navigation("HeSoPhatThaiTuNhienLieus");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.LCA", b =>
                {
                    b.Navigation("RanhGioiLCAs");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.LoaiChatThai", b =>
                {
                    b.Navigation("ChatThais");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.LoaiLoNung", b =>
                {
                    b.Navigation("LoNungTrongNhaMays");

                    b.Navigation("NhaMays");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.LoaiNguyenLieu", b =>
                {
                    b.Navigation("NguyenLieus");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.LoaiNhaMay", b =>
                {
                    b.Navigation("NhaMays");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.LoaiNhienLieu", b =>
                {
                    b.Navigation("NhienLieus");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.NguyenLieu", b =>
                {
                    b.Navigation("HeSoPhatThaiTuNguyenLieus");

                    b.Navigation("NguyenLieuSanPhams");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.NhaMay", b =>
                {
                    b.Navigation("LoNungTrongNhaMays");

                    b.Navigation("SanPhams");

                    b.Navigation("TieuThuNhienLieuLoNams");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.NhienLieu", b =>
                {
                    b.Navigation("HeSoPhatThaiTuNhienLieus");

                    b.Navigation("NhienLieuSanPhams");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.SanPham", b =>
                {
                    b.Navigation("NguyenLieuSanPhams");

                    b.Navigation("NhienLieuSanPhams");

                    b.Navigation("RanhGioiLCAs");

                    b.Navigation("SanXuatNams");

                    b.Navigation("ThaiDauRas");
                });

            modelBuilder.Entity("VienHoa_Core.Entity.SanXuatNam", b =>
                {
                    b.Navigation("NguyenLieuNams");
                });
#pragma warning restore 612, 618
        }
    }
}
