//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VienHoa.EnumNhaMay {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VienHoa.EnumNhaMay.ErrorInfo", typeof(ErrorInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có một đối tượng cùng thông tin được theo dõi.
        /// </summary>
        internal static string DoiTuongCanThemBiTrung {
            get {
                return ResourceManager.GetString("DoiTuongCanThemBiTrung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tượng cần thao tác không tồn tại trong danh sách quản lý.
        /// </summary>
        internal static string DoiTuongKhongCoTrongDanhSach {
            get {
                return ResourceManager.GetString("DoiTuongKhongCoTrongDanhSach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường vị trí không được quá 150 từ.
        /// </summary>
        internal static string RutGonLaiDiaChiNhaMay {
            get {
                return ResourceManager.GetString("RutGonLaiDiaChiNhaMay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng thu gọn tên nhà máy.
        /// </summary>
        internal static string TenNhaMayQuaDai {
            get {
                return ResourceManager.GetString("TenNhaMayQuaDai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhà máy không được để trống.
        /// </summary>
        internal static string TenNhaMayTrong {
            get {
                return ResourceManager.GetString("TenNhaMayTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác đã được thực hiện.
        /// </summary>
        internal static string ThaoTacThanhCong {
            get {
                return ResourceManager.GetString("ThaoTacThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin chưa được nhập vào.
        /// </summary>
        internal static string ThongTinTrong {
            get {
                return ResourceManager.GetString("ThongTinTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỷ lệ cổ phần đầu vào phải là 1 số thực.
        /// </summary>
        internal static string TyLeCoPhanPhaiLaSoThuc {
            get {
                return ResourceManager.GetString("TyLeCoPhanPhaiLaSoThuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí nhà máy không được để trống.
        /// </summary>
        internal static string ViTriNhaMayTrong {
            get {
                return ResourceManager.GetString("ViTriNhaMayTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn thêm bản ghi này.
        /// </summary>
        internal static string XacNhanThemBanGhi {
            get {
                return ResourceManager.GetString("XacNhanThemBanGhi", resourceCulture);
            }
        }
    }
}
